    version: '3.4'
    services:
      nfs:
        build: .      
        container_name: nfs      
        volumes:
          - ./volume:/nfsshare
        ports:
          - 111:111      
          - 111:111/udp
          - 2049:2049
          - 2049:2049/udp  
          - 32765-32768:32765-32768
          - 32765-32768:32765-32768/udp  
        privileged: true    
        restart: always
